services:

  datadb:
    image: postgres:latest
    environment:
      POSTGRES_USER: rb110
      POSTGRES_DB: rb110
      POSTGRES_PASSWORD: rb110
    ports:
      - 5432:5432
    networks:
      - backend

  ofelia:
    image: mcuadros/ofelia:0.3
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.pull-live-data.schedule: "@every 30s"
      ofelia.job-run.pull-live-data.image: "${DOCKER_USERNAME}/${APPLICATION_NAME}:latest"
      ofelia.job-run.pull-live-data.command: "python createtimetable.py"
      ofelia.job-run.pull-live-data.network: "backend"
      ofelia.smtp-host: "posteo.de"
      ofelia.smtp-port: "465"
      ofelia.smtp-user: "jenspetit@posteo.net"
      ofelia.smtp-password: "${SMTP_PASSWORD}"
      ofelia.email-to: "jenspetit@posteo.de"
      ofelia.email-from: "rb110@posteo.de"
    networks:
      - backend

networks:
  backend:
